# Author:Xiaojingyuan
from YunluFramework_API.public.common.test_excel import Excel
from YunluFramework_API.testcase.SpaceAPI import *


class SpaceAPI_Dada():
    ex = Excel(xls='data_api.xls', sheet_name='SPACE')
    # Space_org_create_data = ex.get_data(description='Space - 企业空间创建')
    # Space_delete_contact_id_data = ex.get_data(description='Space - 空间中删除联系人（删除客户）')
    # Space_add_contac_id_data = ex.get_data(description='Space - 空间中添加联系人（新增客户）')
    # Space_switch_setting_api = ex.get_data(description='Space - 空间公开设置（名片设置）')
    # Space_folder_list_id_data = ex.get_data(description=' Space - 文件夹列表(联系人所有）')
    # Space_folder_browse_data = ex.get_data(description='Space - 文件夹浏览记录')
    Space_private_type_list_data = ex.get_data(description='Space - 空间类型列表（私人空间）')
    # Space_popular_name_data = ex.get_data(description='Space - 热门空间名')
    # Space_private_create_data = ex.get_data(description='Space - 空间创建（私人空间）')
    # Space_list_data = ex.get_data(description='Space - 空间列表')
    # Space_update_id_data = ex.get_data(description='Space - 空间更新（私人空间）')
    # Space_folder_create_data = ex.get_data(description='Space - 文件夹创建')
    # Space_folder_update_id_data = ex.get_data(description=' Space - 文件夹更新')
    # Space_folder_list_data = ex.get_data(description='Space - 文件夹列表')
    # Space_overview_id_data = ex.get_data(description='Space - 空间概况（私人空间）')
    # Space_folder_delete_id_data = ex.get_data(description=' Space - 文件夹删除')
    # Space_private_delete_id_data = ex.get_data(description='Space - 空间删除（私人空间）')

    # Space_org_create_result = ex.get_result(description='Space - 企业空间创建')
    # Space_delete_contact_id_result = ex.get_result(description='Space - 空间中删除联系人（删除客户）')
    # Space_add_contac_id_result = ex.get_result(description='Space - 空间中添加联系人（新增客户）')
    # Space_switch_setting_api = ex.get_result(description='Space - 空间公开设置（名片设置）')
    # Space_folder_list_id_result = ex.get_result(description=' Space - 文件夹列表(联系人所有）')
    # Space_folder_browse_result = ex.get_result(description='Space - 文件夹浏览记录')
    Space_private_type_list_result = ex.get_result(description='Space - 空间类型列表（私人空间）')
    # Space_popular_name_result = ex.get_result(description='Space - 热门空间名')
    # Space_private_create_result = ex.get_result(description='Space - 空间创建（私人空间）')
    # Space_list_result = ex.get_result(description='Space - 空间列表')
    # Space_update_id_result = ex.get_result(description='Space - 空间更新（私人空间）')
    # Space_folder_create_result = ex.get_result(description='Space - 文件夹创建')
    # Space_folder_update_id_result = ex.get_result(description=' Space - 文件夹更新')
    # Space_folder_list_result = ex.get_result(description='Space - 文件夹列表')
    # Space_overview_id_result = ex.get_result(description='Space - 空间概况（私人空间）')
    # Space_folder_delete_id_result = ex.get_result(description=' Space - 文件夹删除')
    # Space_private_delete_id_result = ex.get_result(description='Space - 空间删除（私人空间）')

    list1 = [Space_private_type_list_data, Space_private_type_list_result]
    # print(Space_private_type_list_data)
    # print(type(Space_private_type_list_data))
    # print(list1)
    # print(list1[0])
    # print(list1[1])
    # print(list1[0], list1[1])
